### ISSUE TITLE
OnlineTripletLoss  

### ISSUE THREAD

**Issue by heet2201** [adambielski/siamese-triplet#50]
Hello, I am training on custom data using OnlineTripletLoss, But during loss calculation, I got the following error.

> TypeError: forward() takes 3 positional arguments but 4 were given

![Screenshot_2020-04-26_04-16-40](https://user-images.githubusercontent.com/43903682/80292686-ad802000-8775-11ea-882c-2f1b058c3431.png)

And all feature Functions are as below,

![Screenshot_2020-04-26_04-32-17](https://user-images.githubusercontent.com/43903682/80292847-71e65580-8777-11ea-8f83-82658113a7ba.png)

Can Anyone help with it !!
Thank You.

**Comment by adambielski** [comment]
You should be using EmbeddingNet with OnlineTripletLoss, not TripletNet. See some examples in the notebooks.

**Comment by Trotts** [comment]
Hi @adambielski, sorry for reviving a dead issue but I was wondering if you could explain a bit more why we use EmbeddingNet rather than TripletNet when using OnlineTripletLoss? I ran into the same issue as @heet2201 whereby I used a TripletNet and received the same error before going back to the example notebook and realising my mistake. However, looking through the code I can't seem to find the explanation as to why EmbeddingNet is used rather than TripletNet when using OnlineTripletLoss and a Triplet selector, surely we should be using the predefined TripletNetwork here? Have I missed something obvious?

**Comment by adambielski** [comment]
@Trotts In my implementation TripletNetwork takes a triplet as an input - an anchor, a positive and a negative and returns a triplet of embeddings in the same order; so we need to sample the triplets before feeding them to the network and then we can compute TripletLoss on those specific triplets. All that TripletNetwork does is running the EmbeddingNet for anchors, positive and negative inputs.

If we want to use OnlineTripletLoss, we do not sample the triplest before feeding them to the network, we simply get the embeddings for a batch of images (that's why we use EmbeddingNet that only takes one input and returns one output) and use their labels (in a triplet selector) to create triplets afterwards and compute the loss on the computed embeddings. Now we can use one embedding to compute the loss for multiple triplets.

**Comment by Trotts** [comment]
@adambielski thank you for the swift response! That makes perfect sense, I forgot that images have to be embedded before triplets can be selected, in which case using the EmbeddingNet is obvious!
